export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USERS = "LOGOUT_USERS";
export const LOGOUT_USERS_SUCCESS = "LOGOUT_USERS_SUCCESS";
export const RESET_USERS = "RESET_USERS"